apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: workbc-sam-api-template
labels:
  template: workbc-sam-api
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      shared: true
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    name: ${NAME}${SUFFIX}
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:${TAG}
    postCommit: {}
    resources:
      requests:
        cpu: 1
        memory: 2Gi
      limits:
        cpu: 2
        memory: 4Gi
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      type: Git
    strategy:
      type: Docker
      dockerStrategy: {}
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: workbc-sam-api
- description: A name suffix used for all objects
  displayName: Suffix
  name: SUFFIX
  required: false
  value: ''
- description: Tag used for the image tags
  displayName: tag
  name: TAG
  required: true
  value: latest
- description: SOURCE_REPOSITORY_URL
  displayName: SOURCE_REPOSITORY_URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/bcgov/workbc-sam-api
- description: SOURCE_REPOSITORY_REF
  displayName: SOURCE_REPOSITORY_REF
  name: SOURCE_REPOSITORY_REF
  required: true
  value: main